export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const FETCH_STUDENTS = "FETCH_STUDENTS";
export const CREATE_STUDENT = "CREATE_STUDENT"